### ISSUE TITLE
cl-ledger was removed from Quicklisp (july 2018) (but it should be back)

### ISSUE THREAD

**Issue by vindarel** [ledger/cl-ledger#7]
Hello,

Given http://blog.quicklisp.org/2018/07/july-2018-quicklisp-dist-update-now.html, cl-ledger is "no longer available for download that I could find".

I see you opened an issue: https://github.com/quicklisp/quicklisp-projects/issues/1532

So let's just wait.

**Comment by glv2** [comment]
cl-ledger is back on Quicklisp.
http://blog.quicklisp.org/2018/08/new-projects-cari3s-generator-for-i3.html
