### ISSUE TITLE
read-price problem

### ISSUE THREAD

**Issue by admich** [ledger/cl-ledger#8]
If in aline with price there is also the hours, minutes and second like:
`P 2019/01/16 18:22:00 $ 1.5 EUR`

the program return an error.

**Comment by admich** [comment]
One possible solution is to change `*price-scanner*` to

`(defvar *price-scanner*
  (cl-ppcre:create-scanner
   (format nil "^P (~A)\\s*[0-9:]*\\s+(\\S+)\\s+(.+)$" *date-regexp*)))`

This is not an optimal solution because the time information is parsed but not used, the price moment is at 00:00:00 of the day.

If I try to use time information I have some probelm with function `strptime` in `periods` package that I think don't works properly with some format string.

**Comment by glv2** [comment]
Commit 5e1c6ce410a485f455e61c5e38d1d1169c50eea4 in *cl-legder* and the commit in the pull request https://github.com/jwiegley/periods/pull/11 in *periods* should allow hours, minutes and seconds in dates.

Could you try and see if it solves your issues?

Note that if you want to see the time in the reports, you'll have to bind ```*output-time-format*``` to something like ```"%Y/%m/%d %H:%M:%S"``` (is it ```""%Y/%m/%d"``` by default).

**Comment by admich** [comment]
Yes, with these commits I can read my file with prices and I don't have errors. 

I'm not sure all is working. For example I don't see any differrences in the reports between option `:show :basis` and `:show :market`. 

However for the moment my interest is only in use `cl-ledger` to import ledger files in one my application not in generate report (I usually use c++ ledger program for that).

Thank you for the the fix.
